### ISSUE TITLE
Compare functionality not working 

### ISSUE THREAD

**Issue by ashudev** [pegasystems/pega-tracerviewer#1]
Compare functionality is not showing all the events

![table_view](https://user-images.githubusercontent.com/8074662/29655862-b8f970c0-88f5-11e7-9e86-e218093a1f68.PNG)

![compare](https://user-images.githubusercontent.com/8074662/29655857-b39b871c-88f5-11e7-9507-e49692202f62.PNG)

**Comment by vargm** [comment]
Fixed in /releases/pega-tracerviewer-3.1
